services:
  - type: web
    name: yassine-portfolio-api
    runtime: node
    plan: free
    rootDir: server
    autoDeployTrigger: commit
    healthCheckPath: /api
    buildCommand: npm install && npm run prisma:generate && npm run build
    preDeployCommand: npm run prisma:push && npm run prisma:seed
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
